global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8080
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
